# Generated by Django 2.2.4 on 2021-04-18 18:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCartao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=200, null=True)),
                ('codcontafinanceira', models.CharField(blank=True, db_column='CodContaFinanceira', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TiposCartao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('cod_bairro', models.CharField(blank=True, db_column='CodBairro', max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=200, null=True)),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=5, null=True)),
                ('numeroregisto', models.CharField(blank=True, db_column='NumeroRegisto', max_length=50, null=True)),
                ('swiftcode', models.CharField(blank=True, db_column='SwiftCode', max_length=10, null=True)),
                ('codbanco', models.CharField(blank=True, db_column='CodBanco', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='CartaConducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numlicenca', models.CharField(blank=True, db_column='NumLicenca', max_length=50, null=True)),
                ('dataemissao', models.DateField(blank=True, db_column='DataEmissao', null=True)),
                ('dataprimeiraemissao', models.DateField(blank=True, db_column='DataPrimeiraEmissao', null=True)),
                ('datavalidade', models.DateField(blank=True, db_column='DataValidade', null=True)),
                ('caminhoficheiro', models.CharField(blank=True, db_column='CaminhoFicheiro', max_length=256, null=True)),
                ('codcartaconducao', models.CharField(blank=True, db_column='CodCartaConducao', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'CartaConducao',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('codcidade', models.CharField(blank=True, db_column='CodCidade', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codendereco', models.CharField(blank=True, db_column='CodEndereco', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='EntidadeEmissora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=200, null=True)),
                ('codentidadeemissora', models.CharField(blank=True, db_column='CodEntidadeEmissora', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'EntidadeEmissora',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codestadocivil', models.CharField(blank=True, db_column='CodEstadoCivil', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'EstadoCivil',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codGenero', models.CharField(blank=True, db_column='CodGenero', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('codigopais', models.CharField(blank=True, db_column='CodigoPais', max_length=5, null=True)),
                ('ddd', models.CharField(blank=True, db_column='DDI', max_length=5, null=True)),
                ('codpais', models.CharField(blank=True, db_column='CodPais', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='RestricoesCategorias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=5, null=True)),
                ('codrestricoescategorias', models.CharField(blank=True, db_column='CodRestricoesCategorias', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'RestricoesCategorias',
            },
        ),
        migrations.CreateModel(
            name='RestricoesPessoais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=5, null=True)),
                ('codrestricoespessoais', models.CharField(blank=True, db_column='CodRestricoesPessoais', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'RestricoesPessoais',
            },
        ),
        migrations.CreateModel(
            name='RestricoesViaturas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=5, null=True)),
                ('codrestricoesviaturas', models.CharField(blank=True, db_column='CodRestricoesViaturas', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'RestricoesViaturas',
            },
        ),
        migrations.CreateModel(
            name='TipoContactos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codtipocontacto', models.CharField(blank=True, db_column='CodTipoContacto', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TipoContactos',
            },
        ),
        migrations.CreateModel(
            name='TiposCartaConducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=5, null=True)),
                ('codtiposcartaconducao', models.CharField(blank=True, db_column='CodTiposCartaConducao', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TiposCartaConducao',
            },
        ),
        migrations.CreateModel(
            name='TiposConta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=100, null=True)),
                ('codtipoconta', models.CharField(blank=True, db_column='CodTipoConta', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TiposConta',
            },
        ),
        migrations.CreateModel(
            name='TiposEndereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipoendereco', models.CharField(blank=True, db_column='TipoEndereco', max_length=100, null=True)),
                ('codtipoEndereco', models.CharField(blank=True, db_column='CodTipoEndereco', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TiposEndereco',
            },
        ),
        migrations.CreateModel(
            name='TiposSanguineos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiposanguineo', models.CharField(blank=True, db_column='TipoSanguineo', max_length=5, null=True)),
                ('codtiposanguineo', models.CharField(blank=True, db_column='CodTipoSanguineo', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='dataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='ataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'TiposSanguineos',
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
                ('abreviacao', models.CharField(blank=True, db_column='Abreviacao', max_length=50, null=True)),
                ('codtitulo', models.CharField(blank=True, db_column='CodTitulo', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Titulos',
            },
        ),
        migrations.CreateModel(
            name='User_permissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', through='Api.User_permissions', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user_permissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ruas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('codrua', models.CharField(blank=True, db_column='CodRua', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('bairroid', models.ForeignKey(blank=True, db_column='BairroId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Bairros')),
            ],
            options={
                'db_table': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='RestricoesViaturaCartaConducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codrestricoesviaturacartaconducao', models.CharField(blank=True, db_column='CodRestricoesViaturaCartaConducao', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('cartaconducaoid', models.ForeignKey(blank=True, db_column='CartaConducaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.CartaConducao')),
                ('restricoesviaturaid', models.ForeignKey(blank=True, db_column='RestricoesViaturaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.RestricoesViaturas')),
            ],
            options={
                'db_table': 'RestricoesViaturaCartaConducao',
            },
        ),
        migrations.CreateModel(
            name='RestricoesPessoaisCartaConducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codrestricoespessoaiscartaconducao', models.CharField(blank=True, db_column='CodRestricoesPessoaisCartaConducao', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('cartaconducaoid', models.ForeignKey(blank=True, db_column='CartaConducaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.CartaConducao')),
                ('restricoespessoaisid', models.ForeignKey(blank=True, db_column='RestricoesPessoaisId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.RestricoesPessoais')),
            ],
            options={
                'db_table': 'RestricoesPessoaisCartaConducao',
            },
        ),
        migrations.CreateModel(
            name='RestricoesCategoriasCartaConducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codrestricoescategoriascartaconducao', models.CharField(blank=True, db_column='CodRestricoesCategoriasCartaConducao', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('cartaconducaoid', models.ForeignKey(blank=True, db_column='CartaConducaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.CartaConducao')),
                ('restricoescategoriasid', models.ForeignKey(blank=True, db_column='RestricoesCategoriasId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.RestricoesCategorias')),
            ],
            options={
                'db_table': 'RestricoesCategoriasCartaConducao',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('codprovincia', models.CharField(blank=True, db_column='CodProvincia', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('paisid', models.ForeignKey(blank=True, db_column='PaisId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Paises')),
            ],
            options={
                'db_table': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primeironome', models.CharField(blank=True, db_column='PrimeiroNome', max_length=100, null=True)),
                ('nomedomeio', models.CharField(blank=True, db_column='NomeDoMeio', max_length=100, null=True)),
                ('ultimonome', models.CharField(blank=True, db_column='UltimoNome', max_length=100, null=True)),
                ('nomecompleto', models.CharField(blank=True, db_column='NomeCompleto', max_length=200, null=True)),
                ('nomecurto', models.CharField(blank=True, db_column='NomeCurto', max_length=100, null=True)),
                ('pseudonimo', models.CharField(blank=True, db_column='Pseudonimo', max_length=100, null=True)),
                ('datanascimento', models.DateField(blank=True, db_column='DataNascimento', null=True)),
                ('nif', models.CharField(blank=True, db_column='NIF', max_length=50, null=True, unique=True)),
                ('numsegurancasocial', models.CharField(blank=True, db_column='NumSegurancaSocial', max_length=50, null=True)),
                ('codpessoa', models.CharField(blank=True, db_column='CodPessoa', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('estadocivilid', models.ForeignKey(blank=True, db_column='EstadoCivilId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.EstadoCivil')),
                ('generoid', models.ForeignKey(blank=True, db_column='GeneroId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Generos')),
                ('tiposanguineoid', models.ForeignKey(blank=True, db_column='TipoSanguineoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TiposSanguineos')),
                ('tituloid', models.ForeignKey(blank=True, db_column='TituloId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Titulos')),
            ],
            options={
                'db_table': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('codmunicipio', models.CharField(blank=True, db_column='CodMunicipio', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('provinciaid', models.ForeignKey(blank=True, db_column='ProvinciaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Provincias')),
            ],
            options={
                'db_table': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codmotorista', models.CharField(blank=True, db_column='CodMotorista', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('pessoaid', models.ForeignKey(blank=True, db_column='PessoaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Pessoa')),
            ],
            options={
                'db_table': 'Motorista',
            },
        ),
        migrations.CreateModel(
            name='Moradas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeroporta', models.IntegerField(blank=True, db_column='NumeroPorta', null=True)),
                ('numerocasa', models.IntegerField(blank=True, db_column='NumeroCasa', null=True)),
                ('caixapostal', models.IntegerField(blank=True, db_column='CaixaPostal', null=True)),
                ('numeroandar', models.IntegerField(blank=True, db_column='NumeroAndar', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('pontoreferencia', models.CharField(blank=True, db_column='PontoReferencia', max_length=100, null=True)),
                ('codmunicipio', models.CharField(blank=True, db_column='CodMunicipio', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('cidadeid', models.ForeignKey(blank=True, db_column='CidadeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Cidades')),
                ('enderecoid', models.ForeignKey(blank=True, db_column='EnderecoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Enderecos')),
            ],
            options={
                'db_table': 'Moradas',
            },
        ),
        migrations.AddField(
            model_name='enderecos',
            name='ruaid',
            field=models.ForeignKey(blank=True, db_column='RuaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Ruas'),
        ),
        migrations.AddField(
            model_name='enderecos',
            name='tipoenderecoId',
            field=models.ForeignKey(blank=True, db_column='TipoEnderecoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TiposEndereco'),
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('coddistrito', models.CharField(blank=True, db_column='CodDistrito', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('municipioid', models.ForeignKey(blank=True, db_column='municipioid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Municipios')),
            ],
            options={
                'db_table': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refcontafinanceira', models.CharField(blank=True, db_column='RefContaFinanceira', max_length=50, null=True)),
                ('numeroconta', models.IntegerField(blank=True, db_column='NumeroConta', null=True)),
                ('nomeconta', models.CharField(blank=True, db_column='NomeConta', max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('iban', models.CharField(blank=True, db_column='IBAN', max_length=100, null=True)),
                ('nib', models.CharField(blank=True, db_column='NIB', max_length=100, null=True)),
                ('limiteconta', models.FloatField(blank=True, db_column='LimiteConta', null=True)),
                ('dataencerramento', models.DateField(blank=True, db_column='DataEncerramento', null=True)),
                ('codcontafinanceira', models.CharField(blank=True, db_column='CodContaFinanceira', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('bancoid', models.ForeignKey(blank=True, db_column='BancoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Banco')),
                ('tipocontaid', models.ForeignKey(blank=True, db_column='TipoContaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TiposConta')),
                ('titulardacontaid', models.ForeignKey(blank=True, db_column='TitularDaContaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Pessoa')),
            ],
            options={
                'db_table': 'ContaFinanceira',
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telemovel', models.IntegerField(blank=True, db_column='Telemovel', null=True)),
                ('telefone', models.IntegerField(blank=True, db_column='Telefone', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=256, null=True)),
                ('fax', models.IntegerField(blank=True, db_column='Fax', null=True)),
                ('website', models.CharField(blank=True, db_column='WebSite', max_length=256, null=True)),
                ('ddi', models.CharField(blank=True, db_column='DDI', max_length=5, null=True)),
                ('codcontacto', models.CharField(blank=True, db_column='CodContacto', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('pessoaid', models.ForeignKey(blank=True, db_column='PessoaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Pessoa')),
                ('tipocontactoid', models.ForeignKey(blank=True, db_column='TipoContactoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TipoContactos')),
            ],
            options={
                'db_table': 'Contactos',
            },
        ),
        migrations.AddField(
            model_name='cidades',
            name='bairroid',
            field=models.ForeignKey(blank=True, db_column='BairroId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Provincias'),
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True)),
                ('dataexpiracao', models.DateField(blank=True, db_column='DataExpiracao', null=True)),
                ('codcontafinanceira', models.CharField(blank=True, db_column='CodContaFinanceira', max_length=50, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='DataAtualizacao', null=True)),
                ('contafinanceiraid', models.ForeignKey(blank=True, db_column='ContaFinanceiraId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.ContaFinanceira')),
                ('tipocartaoid', models.ForeignKey(blank=True, db_column='TipoCartaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TiposCartao')),
            ],
            options={
                'db_table': 'Cartoes',
            },
        ),
        migrations.AddField(
            model_name='cartaconducao',
            name='entidadeemissoraid',
            field=models.ForeignKey(blank=True, db_column='EntidadeEmissoraId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.EntidadeEmissora'),
        ),
        migrations.AddField(
            model_name='cartaconducao',
            name='motoristaid',
            field=models.ForeignKey(blank=True, db_column='MotoristaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Motorista'),
        ),
        migrations.AddField(
            model_name='cartaconducao',
            name='tipocartaconducaoid',
            field=models.ForeignKey(blank=True, db_column='TipoCartaConducaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.TiposCartaConducao'),
        ),
        migrations.AddField(
            model_name='bairros',
            name='distrito_id',
            field=models.ForeignKey(blank=True, db_column='DistritoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.Distritos'),
        ),
    ]
