# Generated by Django 2.2.4 on 2021-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210418_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='dataatualizacao',
            field=models.DateTimeField(auto_now=True, db_column='DataAtualizacao', null=True),
        ),
        migrations.AlterField(
            model_name='generos',
            name='datacriacao',
            field=models.DateTimeField(auto_now_add=True, db_column='DataCriacao', null=True),
        ),
    ]
